// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateTxHandlerFunc turns a function with the right signature into a create tx handler
type CreateTxHandlerFunc func(CreateTxParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateTxHandlerFunc) Handle(params CreateTxParams) middleware.Responder {
	return fn(params)
}

// CreateTxHandler interface for that can handle valid create tx params
type CreateTxHandler interface {
	Handle(CreateTxParams) middleware.Responder
}

// NewCreateTx creates a new http.Handler for the create tx operation
func NewCreateTx(ctx *middleware.Context, handler CreateTxHandler) *CreateTx {
	return &CreateTx{Context: ctx, Handler: handler}
}

/*
	CreateTx swagger:route POST /tx createTx

create transaction
*/
type CreateTx struct {
	Context *middleware.Context
	Handler CreateTxHandler
}

func (o *CreateTx) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateTxParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
