// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTxSuccess create tx success
//
// swagger:model CreateTxSuccess
type CreateTxSuccess struct {

	// new balance from
	// Required: true
	NewBalanceFrom *int64 `json:"new_balance_from"`

	// new balance to
	// Required: true
	NewBalanceTo *int64 `json:"new_balance_to"`
}

// Validate validates this create tx success
func (m *CreateTxSuccess) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewBalanceFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNewBalanceTo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTxSuccess) validateNewBalanceFrom(formats strfmt.Registry) error {

	if err := validate.Required("new_balance_from", "body", m.NewBalanceFrom); err != nil {
		return err
	}

	return nil
}

func (m *CreateTxSuccess) validateNewBalanceTo(formats strfmt.Registry) error {

	if err := validate.Required("new_balance_to", "body", m.NewBalanceTo); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create tx success based on context it is used
func (m *CreateTxSuccess) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTxSuccess) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTxSuccess) UnmarshalBinary(b []byte) error {
	var res CreateTxSuccess
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
