// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Tx tx
//
// swagger:model Tx
type Tx struct {

	// from
	// Required: true
	// Pattern: ^[0-9a-f]{32}$
	From *string `json:"from"`

	// to
	// Required: true
	// Pattern: ^[0-9a-f]{32}$
	To *string `json:"to"`

	// value
	// Required: true
	// Minimum: 0
	Value *int64 `json:"value"`
}

// Validate validates this tx
func (m *Tx) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFrom(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tx) validateFrom(formats strfmt.Registry) error {

	if err := validate.Required("from", "body", m.From); err != nil {
		return err
	}

	if err := validate.Pattern("from", "body", *m.From, `^[0-9a-f]{32}$`); err != nil {
		return err
	}

	return nil
}

func (m *Tx) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("to", "body", m.To); err != nil {
		return err
	}

	if err := validate.Pattern("to", "body", *m.To, `^[0-9a-f]{32}$`); err != nil {
		return err
	}

	return nil
}

func (m *Tx) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	if err := validate.MinimumInt("value", "body", *m.Value, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tx based on context it is used
func (m *Tx) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Tx) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tx) UnmarshalBinary(b []byte) error {
	var res Tx
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
